### ISSUE TITLE
טמקא new ads

### ISSUE THREAD

**Issue by doronhagag** [easylist/EasyListHebrew#189]
Hey,
טמקא changed some ads, please add the following:
## div[id^="dclk"]

https://iystorage.com

The domain is used serving iframes with ads

Cheers

**Comment by Yaron10** [comment]
http://www.ynet.co.il/home/0,7340,L-5363,00.html
https://s21.postimg.org/uch6quvkn/image.png

**Comment by doronhagag** [comment]
You can add the custom rules until it's updated in the list

**Comment by Yaron10** [comment]
I've done that.
I wanted to post a URL.

Thanks.

**Comment by adkiller126** [comment]
עוד פעם עידכון דומיינים - @IsraeliAdblocker 
אפשר להמשיך ולרדוף.... 
הפתרון היחיד הוא חסימה של כל דומיין צד שלישי שלא מאושר.

**Comment by adkiller126** [comment]
New domain - kozikar.com
![10](https://cloud.githubusercontent.com/assets/19250084/18669091/f3ed3cca-7f41-11e6-8f18-2f9ed00ae213.png)

**Comment by idan-hartzvi** [comment]
The new domain is kozikar.com
please add the following rule to the list:
||kozikar.com^$third-party

Thanks

**Comment by adkiller126** [comment]
NEW DOMAIN - Again, this method is useless. please find better generic way. 
This is too easy to them to change the domain every 2 days.
Block all new 3rd party domains.

<img width="797" alt="capture" src="https://cloud.githubusercontent.com/assets/19250084/18826931/a269150e-83d8-11e6-9f58-0c6cf1773492.PNG">

**Comment by doronhagag** [comment]
in my list i have this;

##div[id^="ads"]
##div[id^="dclk"]

which is good anyway in a very generic way but they might change it again

**Comment by Yaron10** [comment]
Using Firefox + uBO - https://github.com/easylist/EasyListHebrew/commit/9d6909e4547ff9b86e476e2666ec42edae55c08b does not affect http://www.ynet.co.il/articles/0,7340,L-4860292,00.html.

Thanks.

**Comment by idan-hartzvi** [comment]
They uses new Technic!
Currently, ABP can't block websockets, only uBlock with uBlock websockets can handle it.
ABP are currently working on update that can handle it too. the release is on matter of days.
The websocket server domain  to block is jquerycdn.co.il

**Comment by Yaron10** [comment]
@idan-hartzvi,

Using Pale Moon 26 + ABP 2.6.6.1, the ads are blocked.

With Firefox 49 + uBO -  `www.ynet.co.il##iframe[src="about:blank"]` blocks them.
How do you use `jquerycdn.co.il`?

Thanks.

**Comment by idan-hartzvi** [comment]
@Yaron10, i don't want to block just the display of the ads. I want to block the network communication itself.
They connect to jquerycdn.co.il via websocket. So I added the address jquerycdn.co.il to the block list of uBlock and the ads disappear.
On ABP, it's not working because ABP cannot block websockets.

**Comment by Yaron10** [comment]
@idan-hartzvi,

Thanks for replying.

Interestingly - using Pale Moon 26 + ABP 2.6.6.1, the ads **are blocked** without `www.ynet.co.il##iframe[src="about:blank"]`.

Best regards.

**Comment by Yaron10** [comment]
The ads are back. :)
http://www.ynet.co.il/home/0,7340,L-5363,00.html

**Comment by idan-hartzvi** [comment]
They probably reads this lines because they just removed the "src='about:blank'" from their iframes.
So first of all, Hi.
Second of all, you probably won't see ads sometimes because they uses this Technic (https://github.com/zswang/jdetects) to detect when the web console is open and then they not showing ads. Maybe they think it's will protect them. Funny.

The real way to defeat them it's to add rule to block all the websocket communication for ynet with the rule `*$websocket,domain=www.ynet.co.il`.
ynet himself wont uses websocket so no damage will append to the content, and they can't start another stupid "changing domains" game.

**Comment by Yaron10** [comment]
@idan-hartzvi,

`*$websocket,domain=www.ynet.co.il` works well.

@IsraeliAdblocker,

Could you please remove the obsolete ynet filters from the list?

Thank you.
