### ISSUE TITLE
Ads on Mako

### ISSUE THREAD

**Issue by koka99** [easylist/EasyListHebrew#198]
![321321](https://cloud.githubusercontent.com/assets/22445467/18830930/b624148c-83eb-11e6-8e1e-4783058a11af.png)

**Comment by koka99** [comment]
Maybe it has to do with updating Chrome to 53.0.2785.116 ?

**Comment by YoYo06** [comment]
I have the same problem :(
And when you try to use "block element" you click on the element and....it opens it in a new tab.

**Comment by IsraeliUser** [comment]
Please use uBlock Origin (uBO).
Currently, ABP cannot block those ads.

**Comment by koka99** [comment]
Do you know why ABP cannot block those ads?

**Comment by YoYo06** [comment]
Now its even worse....they have commercials also on the VOD..... :(

**Comment by YoYo06** [comment]
Any updates with regards to Mako adds? They just don't stop showing up :(

![1](https://cloud.githubusercontent.com/assets/22640964/19823395/041b222c-9d71-11e6-85c7-5890a310c6d4.jpg)

![2](https://cloud.githubusercontent.com/assets/22640964/19823400/0b260e4c-9d71-11e6-81c5-1420612d768e.jpg)

**Comment by IsraeliUser** [comment]
browser? ad blocker?

**Comment by shaygam22** [comment]
I tell you what, the first page in MAKO,  i don't  see a Ads, but when i
surf to other page in mako, they really annoying!!!
The thing that most annoying is, when i read any article in mako, the page
always jumping up and down, every couple second (because the ADS), but when
i move to MX5 its more better from mx4 version but still showing ads like
in the picture and page jumping less then mx4

The picture is from MX5 v5.0.1.3000

I want to tell you, that surf to MAKO in EDGE browser + (ABP), is worse
then from MX5 + (ABP).
see on the pictur from EDGE browser that i add.

בתאריך 30 באוק׳ 2016 00:54,‏ "IsraeliUser" <notifications@github.com> כתב:

**Comment by YoYo06** [comment]
I completely identify with what shaygam22 wrote just above!  I have the exact same problem.

And for IsraeliUser, I use Windows 10, Chrome  54.0.2840.87 and Adguard add blocker.

Please help us with a solution to this annoying problem :(

Thanks,

YoYo

**Comment by YoYo06** [comment]
Any news with regards to Mako?
