### ISSUE TITLE
walla.co.il - emails - comments - and a lot more doesnt work 

### ISSUE THREAD

**Issue by amnonste** [easylist/EasyListHebrew#286]
After the last commit when you blocked all iframes the entire site doesn't work properly .
You can check the mail page , when you try to send an email the iframe is hidden .
And also some pages on the site are broken because of that.

**Comment by amnonste** [comment]
@IsraeliUser 
Again on the last commit some pages are broken (you can see here for example "https://sports.walla.co.il/" a lot of harmless iframes are hidden), Other than that using #iframe to hide the ad is annoying because i can hear it but cant skip it. 
so my suggestion is : 
walla.co.il##script:inject(abort-on-property-read.js, isMobileasokita)

**Comment by amnonste** [comment]
@IsraeliUser 
You should probably open a new issue in the ublock git with those filters because all adblockers except ublock breaks with those filters

**Comment by amnonste** [comment]
@IsraeliUser 
Hi, again after the last commit a lot of harmless iframes are hidden , examples here: https://buzzit.walla.co.il/item/3149406 , and here : https://play.walla.co.il/item/3142854 .....
our previous filter works perfectly , i think hiding the iframe is bad practice  for both site functionality and you lose the ability to skip the ad and just freeze the video.

**Comment by amnonste** [comment]
@IsraeliUser ++

**Comment by amnonste** [comment]
@IsraeliUser @yuval34 
I'm using Ublock with specific filters that disables the connection, But your'e still right nonetheless .
Hiding the iframe again like the last commit will not only break harmless iframes but in adblock plus will also just freeze the video until the ad finish without the ability to skip thats quite annoying and stupid.
And "Mako" doesn't have those filters so yes you can just skip the ad , if those iframe filters remains then consider moving to ublock or just wait for a couple of minutes every time you want to watch a video :)

**Comment by IsraeliAdblocker** [comment]
@amnonste and @yuval34 , we are working together with ABP dev team in order to provide a solution for those videos pretty soon, watch for an update.
As for walla, specifically in this domain, their WEBRTC connection on ABP causes endless video ads sometimes on my side, the only way to avoid it was to hide the Iframe entirely.
Again, this is for the short period.

**Comment by yuval34** [comment]
@IsraeliAdblocker 
That’s great news, but until then can you remove the filter that causes this to happen because i need to turn off adblock plus in order to watch videos and then i’m getting all other ads , i would preffer and i think everyone will preffer the ability to skip the ads and watch the video and not wait a couple of minutes for the ad to finish in order to watch the video. 
Thanks a lot.

**Comment by yuval34** [comment]
@IsraeliUser
I can’t remove that specific rule? I really love adblock plus and I can’t watch videos anymore without waiting a couple of minutes .

**Comment by yuval34** [comment]
@IsraeliUser @IsraeliAdblocker 
Hey you guys:)
after @IsraeliUser last update 10 days ago everything worked great but now its stuck again and i need to wait for the ad to finish instead of just skipping it.
There is no way to disable that specific filter?
