### ISSUE TITLE
block saturday and holiday block scripts

### ISSUE THREAD

**Issue by kaerez** [easylist/EasyListHebrew#332]
block dns requests to:
http://www.holyclock.com/
http://www.shomershabes.com/

**Comment by IsraeliUser** [comment]
Out of project scope.

To be fixed by:
Fanboy’s Annoyance List @ryanbr 
uBlock Origin - Annoyances​​​​​​​​​ @mapx- @okiehsch
AdGuard Annoyances @AdamWr @Alex-302 @BlazDT @zloyden

I think 3rd-party blocking of the mentioned domain names is the right solution.
The first one is already included in uBlock Origin - Annoyances.

**Comment by IsraeliUser** [comment]
@mapx- @Alex-302
You both added `shomershabes.co.il`.
I think you should also add `shomershabes.com`.
I think they use two domain names (`.co.il` and `.com`).

Thanks!

**Comment by IsraeliUser** [comment]
@mapx-
`||shomershabes.*^$3p` will likely cause false positives. It's a common phrase.
Please use instead:
`||shomershabes.com^$3p`
`||shomershabes.co.il^$3p`

Thanks!
